CREATE DATABASE POOP-SHEET;

CREATE SEQUENCE POOPID START 1;
CREATE SEQUENCE USERID START 1;
CREATE SEQUENCE GROUPID START 1;
CREATE SEQUENCE LIKES START 1;
CREATE SEQUENCE COMMENTS START 1;

CREATE TABLE USERS (
    USERID INTEGER UNIQUE
    , USER_NAME VARCHAR(20) UNIQUE
    , EMAIL VARCHAR(500) UNIQUE
    , DATE_ADDED TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    , IS_ACTIVE BOOLEAN DEFAULT TRUE
    , PRIMARY KEY(USERID, USER_NAME, EMAIL)
);

CREATE TABLE GROUPS (
    GROUPNAME VARCHAR(255) UNIQUE
    , GROUPID INTEGER UNIQUE
    , DATE_CREATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP

    , PRIMARY KEY (GROUPNAME, GROUPID)
);

CREATE TABLE GROUP_MEMBERS (
    GROUPID INTEGER REFERENCES GROUPS(GROUPID)
    , USERID INTEGER REFERENCES USERS(USERID)

    , PRIMARY KEY (GROUPID, USERID)
);

CREATE TABLE POOPS (
     
      ROWNUM INTEGER DEFAULT NEXTVAL('POOPID')
    , USERID INTEGER REFERENCES USERS(USERID) 
    , COMMENT VARCHAR(500)
    , DATE_ADDED TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    , IS_RETRO BOOLEAN DEFAULT FALSE
    , LIKE_COUNT INTEGER DEFAULT 0
    , COMMENT_COUNT INTEGER DEFAULT 0

    , PRIMARY KEY (ROWNUM, USERID)
);

CREATE TABLE LIKES (

    LIKEID INTEGER DEFAULT NEXTVAL('LIKES')
    , POOPID INTEGER REFERENCES POOPS(ROWNUM)
    , USERID INTEGER REFERENCES USERS(USERID)
    , DATE_LIKED TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    , PRIMARY KEY (LIKEID, POOPID, USERID)
);

CREATE TABLE COMMENTS (

    COMMENTID INTEGER DEFAULT NEXTVAL('COMMENTS')
    , COMMENT VARCHAR(3000) NOT NULL
    , POOPID INTEGER REFERENCES POOPS(ROWNUM)
    , USERID INTEGER REFERENCES USERS(USERID)
    , DATE_COMMENTED TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    , PRIMARY KEY (COMMENTID, POOPID, USERID)
);

